project:
  type: website
  output-dir: ../../docs

website:
  title: "Trabalho Prático 1"
  navbar:
    left:
      - href: index.qmd
        text: Relatório
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



