---
title: "Trabalho Prático 1"
subtitle: "Manipulação de sequências"
---

##### **Alunos:** Marcos Paulo Ferreria de Souza, Christian David Costa Vieira


# Introdução

Este relatório apresenta a implementação de um algoritmo de compressão e de uma estrutura de dados. O algoritmo de compressão elaborado é o LZW, que funciona identificando os padrões repetidos em um arquivo e os substituindo por identificadores únicos, gerando assim uma versão comprimida do arquivo. A Trie Compacta, usada para otimizar a compressão, é uma estrutura de dados que armazena de maneira eficiente e compacta os padrões e identificadores gerados pelo algoritmo.

# Implementação

Para realizar a implementação foi utilizado a linguagem de programação Python. Quatro arquivos distintos foram criados para organizar e facilitar a escrita do programa. O arquivo que será executado é o “main.py” que processa as entradas e chama o “lzw.py” que realiza a compressão.A leitura do arquivo de entrada é feita utilizando o “io_manip.py” e o “trieCompacta.py” é usado para armazenar os padrões e os identificadores usados na compressão e a descompressão. A lógica e as decisões que foram feitas na escrita dos códigos “lzw.py” e o “trieCompacta.py” serão explicados nas próximas seções.

# LZW

O algoritmo de compressão foi implementado no arquivo “lzw.py”. O funcionamento do algoritmo se dá pela leitura dos bytes do arquivo de entrada e pela associação desses bytes a identificadores que serão registrados no arquivo comprimido. Sendo que os bytes são associados em sequências que se repetem ao longo do arquivo, ou seja, uma sequência de bytes possui um identificador único e sempre que essa sequência se repetir no arquivo ela será substituída pelo mesmo identificador. Os identificadores associados a apenas uma sequência garante que a compressão seja reversível. A descompressão segue a mesma lógica mas de forma inversa, todo identificador lido do arquivo é traduzido pelo padrão que ele identifica, assim reconstruindo o arquivo original.

# Trie Compacta

A Trie Compacta foi implementada como uma árvore composta por nós que possuem apenas três campos, a chave, o valor e uma lista de nós filhos. Por definição, a Trie Compacta é uma árvore de prefixos, por tanto cada nó vai ter como chave o maior prefixo compartilhado entre os seus nós filhos e apenas as folhas vão possuir valores. Seguindo essas definições foram implementadas as funções de inserção, remoção e pesquisa de chaves na árvore. Caso a mesma chave seja inserida mais de uma vez, ela irá possuir como os seus N primeiros filhos, sendo N o número de vezes que a chave foi inserida na árvore, nós com a chave vazia e que possuem os valores associados a chave nas diferentes inserções. Caso uma chave que foi inserida mais de uma vez seja removida todos os valores associados a ela serão removidos, ou seja, independentemente de quantas vezes uma chave foi inserida na árvore ao ser removido todos os valores associados a ela serão retirados da árvore.

# Resultados

Foram feitos dois testes, o primeiro com um arquivo .txt com <tamanho> MB e o segundo com um arquivo .tiff com <tamanho> MB. Os arquivos foram comprimidos com uma taxa de compressão superior a <X> % sendo o arquivo <.txt.> o que mais comprimiu com <X> % de taxa de compressão e o arquivo <.txt.> comprimiu com <X> % de taxa de compressão. A descompressão foi feita com sucesso retornando o mesmo arquivo que foi passado na entrada do algoritmo.
